/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.0
 * $ pg-to-ts generate -c postgres://username:password@localhost:5432/allmagen -t event -t impression -s public
 *
 */


export type Json = unknown;

// Table event
export interface Event {
  uid: string;
  tag: string | null;
}
export interface EventInput {
  uid: string;
  tag?: string | null;
}
const event = {
  tableName: 'event',
  columns: ['uid', 'tag'],
  requiredForInsert: ['uid'],
  primaryKey: 'uid',
  foreignKeys: {},
  $type: null as unknown as Event,
  $input: null as unknown as EventInput
} as const;

// Table impression
export interface Impression {
  uid: string;
  reg_time: Date | null;
  fc_imp_chk: string | null;
  fc_time_chk: string | null;
  utmtr: string | null;
  mm_dma: string | null;
  osname: string | null;
  model: string | null;
  hardware: string | null;
  site_id: string | null;
}
export interface ImpressionInput {
  uid: string;
  reg_time?: Date | null;
  fc_imp_chk?: string | null;
  fc_time_chk?: string | null;
  utmtr?: string | null;
  mm_dma?: string | null;
  osname?: string | null;
  model?: string | null;
  hardware?: string | null;
  site_id?: string | null;
}
const impression = {
  tableName: 'impression',
  columns: ['uid', 'reg_time', 'fc_imp_chk', 'fc_time_chk', 'utmtr', 'mm_dma', 'osname', 'model', 'hardware', 'site_id'],
  requiredForInsert: ['uid'],
  primaryKey: 'uid',
  foreignKeys: {},
  $type: null as unknown as Impression,
  $input: null as unknown as ImpressionInput
} as const;


export interface TableTypes {
  event: {
    select: Event;
    input: EventInput;
  };
  impression: {
    select: Impression;
    input: ImpressionInput;
  };
}

export const tables = {
  event,
  impression,
}
